### ISSUE TITLE
Visual Studio Error

### ISSUE THREAD

**Issue by zicos77** [svnscha/chiaki-dependencies#1]
hi, 
thanks for dependencies :)

I have error with protobuf (#include <takion.pb.h>)
Gravité Code Description Projet Fichier Ligne État de la suppression
Erreur (active) E1696 impossible d'ouvrir le fichier source "takion.pb.h" chiaki-lib C:...\chiaki-master\lib\src\senkusha.c 29

Image :
![image](https://user-images.githubusercontent.com/19989094/73134495-6b8cf400-4037-11ea-8392-04485c54641c.png)

**Comment by svnscha** [comment]
This repository just builds the chiaki-dependencies on Windows to have them prebuilt. You still have to make a proper CMAKE file with prefixes and such to find all the libraries during the chiaki build.

**Comment by zicos77** [comment]
ok, thank
